export const EVENT_IDEAS = [
  {
    id: "dinner",
    category: "meal" as const,
    title_en: "Community dinner",
    title_es: "Cena comunitaria",
    description_en: "Bring a dish if you can, or just bring yourself. We eat together at the garden table.",
    description_es: "Trae un plato si puedes, o simplemente ven. Comemos juntos en la mesa del jardín.",
  },
  {
    id: "seed",
    category: "workshop" as const,
    title_en: "Seed swap",
    title_es: "Intercambio de semillas",
    description_en: "Trade seeds, share what grew well, and leave with something new to plant.",
    description_es: "Intercambia semillas, cuenta lo que creció bien y llévate algo nuevo para sembrar.",
  },
  {
    id: "compost",
    category: "workshop" as const,
    title_en: "Composting workshop",
    title_es: "Taller de composta",
    description_en: "A short lesson on what to compost, how to turn the pile, and how to use the finished soil.",
    description_es: "Una lección breve sobre qué compostar, cómo voltear la pila y cómo usar la tierra terminada.",
  },
  {
    id: "kids",
    category: "workshop" as const,
    title_en: "Kids planting day",
    title_es: "Día de siembra para niñas y niños",
    description_en: "Families welcome. We will plant, water, and send everyone home a little muddy.",
    description_es: "Familias bienvenidas. Vamos a sembrar, regar y volver a casa con un poco de tierra en las manos.",
  },
  {
    id: "harvest",
    category: "meal" as const,
    title_en: "Harvest share",
    title_es: "Reparto de cosecha",
    description_en: "Gather what is ready and share it with neighbors. No gardening experience needed.",
    description_es: "Juntamos lo que ya está listo y lo compartimos con el vecindario. No necesitas experiencia.",
  },
  {
    id: "workday",
    category: "workday" as const,
    title_en: "Volunteer workday",
    title_es: "Jornada de voluntariado",
    description_en: "Weeding, watering, and fixing beds. Tools are here. Come for an hour or stay the morning.",
    description_es: "Deshierbar, regar y arreglar camas. Las herramientas están aquí. Ven una hora o quédate la mañana.",
  },
];
